FlightBookingApp/Controllers/FlightController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FlightBookingApp.ApplicationDbContext;
using FlightBookingApp.Models;
using Newtonsoft.Json;
using System.Text;

namespace FlightBookingApp.Controllers
{
    public class FlightsController : Controller
    {
        public async Task<IActionResult> Index()
        {

            List<Flight> FlightList = new List<Flight>();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:7143/api/Flight"))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    FlightList = JsonConvert.DeserializeObject<List<Flight>>(apiresponse);
                }
            }
            return View(FlightList);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Flight flight)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(flight), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PostAsync("http://localhost:7143/api/Flight", content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    //studentList = JsonConvert.DeserializeObject<List<Student>>(apiresponse);
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Edit(int id)
        {
            Flight flight = new Flight();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:7143/api/Flight/" + id))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    flight = JsonConvert.DeserializeObject<Flight>(apiresponse);
                }
            }

            return View(flight);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Flight flight)
        {
            using (var httpClient = new HttpClient())
            {
                StringContent content = new StringContent(JsonConvert.SerializeObject(flight), Encoding.UTF8, "application/json");
                using (var response = await httpClient.PutAsync("http://localhost:7143/api/Flight/" + id, content))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    //studentList = JsonConvert.DeserializeObject<List<Student>>(apiresponse);
                }
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Details(int id)
        {
            Flight flight = new Flight();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:7143/api/Flight" + id))
                {
                    string apiresponse = await response.Content.ReadAsStringAsync();
                    flight = JsonConvert.DeserializeObject<Flight>(apiresponse);
                }
            }

            return View(flight);
        }

        public async Task<IActionResult> Delete(int id)
        {
            Flight fli = new Flight();
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.GetAsync("http://localhost:7143/api/Flight/" + id))
                {
                    string apiResponse = await response.Content.ReadAsStringAsync();
                    fli = JsonConvert.DeserializeObject<Flight>(apiResponse);
                }
            }
            return View(fli);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            using (var httpClient = new HttpClient())
            {
                using (var response = await httpClient.DeleteAsync("http://localhost:7143/api/Flight/" + id))
                {

                }
            }
            return RedirectToAction("Index");
        }
    }
}

FlightBookingApp/Views/Shared/_Admin.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>

    <!-- Bootstrap Core CSS -->
    <link href="~/css/bootstrap.css" rel='stylesheet' type='text/css' />

    <!-- Custom CSS -->
    <link href="~/css/style.css" rel='stylesheet' type='text/css' />

    <!-- font-awesome icons CSS -->
    <link href="~/css/font-awesome.css" rel="stylesheet">
    <!-- //font-awesome icons CSS-->
    <!-- side nav css file -->
    <link href='~/css/SidebarNav.min.css' media='all' rel='stylesheet' type='text/css' />
    <!-- //side nav css file -->
    <!-- js-->
    <script src="~/js/jquery-1.11.1.min.js"></script>
    <script src="~/js/modernizr.custom.js"></script>

    <!--webfonts-->
    <link href="//fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i&amp;subset=cyrillic,cyrillic-ext,latin-ext" rel="stylesheet">
    <!--//webfonts-->
    <!-- chart -->
    <script src="~/js/Chart.js"></script>
    <!-- //chart -->
    <!-- Metis Menu -->
    <script src="~/js/metisMenu.min.js"></script>
    <script src="~/js/custom.js"></script>
    <link href="~/css/custom.css" rel="stylesheet">
    <!--//Metis Menu -->
    <style>
        #chartdiv {
            width: 100%;
            height: 295px;
        }
    </style>
    <!--pie-chart --><!-- index page sales reviews visitors pie chart -->
    <script src="~/js/pie-chart.js" type="text/javascript"></script>
    <script type="text/javascript">

    </script>
    <!-- //pie-chart --><!-- index page sales reviews visitors pie chart -->
    <!-- requried-jsfiles-for owl -->
    <link href="~/css/owl.carousel.css" rel="stylesheet">
    <script src="~/js/owl.carousel.js"></script>
    <script>
        $(document).ready(function() {
            $("#owl-demo").owlCarousel({
                items : 3,
                lazyLoad : true,
                autoPlay : true,
                pagination : true,
                nav:true,
            });
        });
    </script>
    <!-- //requried-jsfiles-for owl -->
</head>
<body class="cbp-spmenu-push">

    <div class="main-content">
 <div class="cbp-spmenu cbp-spmenu-vertical cbp-spmenu-left" id="cbp-spmenu-s1">
            <!--left-fixed -navigation-->
            <aside class="sidebar-left">
                <nav class="navbar navbar-inverse">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".collapse" aria-expanded="false">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <h1><a class="navbar-brand" href="index.html"><span class="fa fa-area-chart"></span> JX Travels<span class="dashboard_text">Navigate Your World</span></a></h1>
                    </div>
                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="sidebar-menu">
                            <li class="header">MAIN NAVIGATION</li>
                            <li class="treeview">
                                 <a asp-controller="Admin" asp-action="Dashboard"> 
                                    <i class="fa fa-dashboard"></i><span>My Admin Panel</span>
                                 </a>
                            </li>
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-laptop"></i>
                                    <span>AirLines</span>
                                    <i class="fa fa-angle-left pull-right"></i>
                                </a>
                                <ul class="treeview-menu">
                                    <li class="fa fa-angle-right">@Html.ActionLink("Add", "login", "Admin")</li>
                                    @* <li><a href="~/Views/Admin/login.cshtml"><i class="fa fa-angle-right"></i> Add</a></li> *@
                                    <li><a href="media.html"><i class="fa fa-angle-right"></i> View Details</a></li>
                                    
                                </ul>
                            </li>
                           
                            
                            <li class="treeview">
                                <a href="#">
                                    <i class="fa fa-laptop"></i>
                                    <span>Flights</span>
                                    <i class="fa fa-angle-left pull-right"></i>
                                </a>
                                <ul class="treeview-menu">
                                    <li>@Html.ActionLink("Add Flight", "Create", "Flights")</li>
                                    @* <li><a href="general.html"><i class="fa fa-angle-right"></i> Add</a></li> *@
									@* <li><a href="icons.html"><i class="fa fa-angle-right"></i> View Details</a></li> *@
                                    <li>@Html.ActionLink("View Details", "Index", "Flights")</li>
                                </ul>
                            </li>
                            <li>
                                <a href="widgets.html">
                                    <i class="fa fa-th"></i> <span>Users</span>
                                    
                                </a>
                            </li>
                            
                        </ul>
                    </div>
                    <!-- /.navbar-collapse -->
                </nav>
            </aside>
        </div>
        </div>
    <div class="content">
        @RenderBody()
    </div>
    <div class="footer">
        <p>&copy; Flight Booking. All Rights Reserved |</p>
    </div>
    <!--//footer-->
    

    <!-- new added graphs chart js-->

    <script src="js/Chart.bundle.js"></script>
    <script src="js/utils.js"></script>

    <script>
       
    </script>
    <!-- new added graphs chart js-->
    <!-- Classie --><!-- for toggle left push menu script -->
    <script src="~/js/classie.js"></script>
    <script>
        var menuLeft = document.getElementById('cbp-spmenu-s1'),
            showLeftPush = document.getElementById('showLeftPush'),
            body = document.body;

        showLeftPush.onclick = function () {
            classie.toggle(this, 'active');
            classie.toggle(body, 'cbp-spmenu-push-toright');
            classie.toggle(menuLeft, 'cbp-spmenu-open');
            disableOther('showLeftPush');
        };


        function disableOther(button) {
            if (button !== 'showLeftPush') {
                classie.toggle(showLeftPush, 'disabled');
            }
        }
    </script>
    <!-- //Classie --><!-- //for toggle left push menu script -->
    <!--scrolling js-->
    <script src="~/js/jquery.nicescroll.js"></script>
    <script src="~/js/scripts.js"></script>
    <!--//scrolling js-->
    <!-- side nav js -->
    <script src='~/js/SidebarNav.min.js' type='text/javascript'></script>
    <script>
        $('.sidebar-menu').SidebarNav()
    </script>
    <!-- //side nav js -->
    <!-- for index page weekly sales java script -->
    <script src="~/js/SimpleChart.js"></script>
    <script>
       

    </script>
    <!-- //for index page weekly sales java script -->
    <!-- Bootstrap Core JavaScript -->
    <script src="~/js/bootstrap.js"> </script>
    <!-- //Bootstrap Core JavaScript -->
    @RenderSection("Scripts", required: false)

</body>
</html>

FlightBookingApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] JX Travels</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    @* <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" /> *@
    @* <link rel="stylesheet" href="~/FlightBookingApp.style.css" asp-append-version="true" /> *@
    <link rel="icon" type="image/x-icon" href="~/favicon1.ico" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="
https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css"
          integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/css//hpstyle.css" />

</head>
<body>
    <header>
        <nav>
            @* <img src="~/images/jx-logo.jpg" style="height:50px; width:50px;">&emsp; *@
            <div class="nav__logo">
                <a class="link" asp-area="" asp-controller="Booking" asp-action="SearchForm">
                    <img src="~/images/jx-logo.jpg" style="height:25px; width:25px;">
                    JX TRAVELS
                </a>
            </div>
                <ul class="nav__links">
                <li class="link"><a asp-area="" asp-controller="Home" asp-action="AboutUs">About</a></li>
                <li class="link"><a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a></li>
                <li class="link"><a asp-area="" asp-controller="Home" asp-action="Offers">Offers</a></li>
                <li class="link"><a asp-area="" asp-controller="Home" asp-action="Contactus">  Contact Us </a></li>
                    @* <li class="link">
                    <a asp-area="" asp-controller="Booking" asp-action="SearchForm">Search Flights</a>
                    </li> *@
                    <li class="link">
                        <a class="link" asp-area="" asp-controller="Booking" asp-action="BookingHistory">My Bookings</a>
                    </li>
                    <li class="link">
                        @* <a class="link" asp-area="" asp-controller="Admin" asp-action="login">Admin</a> *@
                        <a class="link" asp-area="" asp-controller="Home" asp-action="Careers">Careers</a>
                    </li>
                </ul>
            <partial name="_LoginPartial" />
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <style>
        .container {
            text-align: left;
        }
    </style>

    <footer class="footer">
        <div class="section__container footer__container">
            <div class="footer__col">
                <h3>JX TRAVEL AGENCY</h3>
                <p>
                    Where Excellence Takes Flight. With a strong commitment to customer
                    satisfaction and a passion for air travel, JX Travels offers
                    exceptional service and seamless journeys.
                </p>
                <p>
                    From friendly smiles to state-of-the-art aircraft, we connect the
                    world, ensuring safe, comfortable, and unforgettable experiences.
                </p>
            </div>
            <div class="footer__col">
                <h4>INFORMATION</h4>
                <a asp-area="" asp-controller="Booking" asp-action="SearchForm"> Home </a><br /><br />
                <a asp-area="" asp-controller="Home" asp-action="AboutUs">About</a><br /><br />
                <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a><br /><br />
                <a asp-area="" asp-controller="Home" asp-action="Contactus">  Contact Us </a><br /><br />
                
            </div>
            <div class="footer__col">
                <h4>HELP</h4>
                <a asp-area="" asp-controller="Home" asp-action="FAQ">FAQs</a><br /><br />
                <a asp-area="" asp-controller="Home" asp-action="Agreement">Terms & Conditions</a>
                
            </div>
        </div>
        <div class="section__container footer__bar">
            <p>Copyright © 2024 JX TRAVEL AGENCY. All rights reserved.</p>
            <div class="socials">
                <i class="fa-brands fa-facebook-f"></i>
                <i class="fa-brands fa-twitter"></i>
                <i class="fa-brands fa-instagram"></i>
                <i class="fa-brands fa-youtube"></i>
            </div>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FlightBookingApp/Views/Shared/_Layout1.cshtml
<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Flight Home Page</title>

    <style>

        body {
            background-image: url("bgimg1.jfif");
            background-repeat: no-repeat;
            background-size: cover;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: navy;
            color: aliceblue;
            padding: 20px;
            text-align: center;
        }

        nav {
            color: aliceblue;
            padding: 9px 0;
            text-align: left;
        }

            nav a {
                color: aliceblue;
                text-decoration: none;
                margin: 0 10px;
            }

        section {
            padding: 20px;
            text-align: center;
            display: flex;
        }

        footer {
            background-color: aliceblue;
            color: navy;
            padding: 20px;
            text-align: right;
            position: relative;
            bottom: 0;
            width: 100%;
            height: 30%;
        }

        .container {
            width: 100%;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: start;
        }

        .flip-card {
            background-color: transparent;
            width: 300px;
            height: 300px;
            perspective: 1000px;
        }

        .flip-card-inner {
            position: relative;
            width: 100%;
            height: 100%;
            text-align: center;
            transition: transform 0.6s;
            transform-style: preserve-3d;
            box-shadow: 0 4px 8px 0 rgba(0,0,0,0.2);
        }

        .flip-card:hover .flip-card-inner {
            transform: rotateY(180deg);
        }

        .flip-card-front, .flip-card-back {
            position: absolute;
            width: 100%;
            height: 100%;
            -webkit-backface-visibility: hidden;
            backface-visibility: hidden;
        }

        .flip-card-front {
            background-color: #bbb;
            color: black;
        }

        .flip-card-back {
            background-color: #2980b9;
            color: white;
            transform: rotateY(180deg);
        }

        .contain {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }

        .btn {
            border: none;
            color: white;
            padding: 12px 16px;
            font-size: 16px;
            cursor: pointer;
        }
    </style>
</head>


<body>

    <header>

        <nav>

            <a href="#"><u>JXTravels</u> </a>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

            <a asp-controller="Flights" asp-action="Create" class="btn btn-info">Add Flights</a>

            <a asp-controller="Flights" asp-action="Index" class="btn btn-info">View Flights</a>


                        

        </nav>

    </header>
    <section>
        &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="images\img2.png" alt="Avatar" style="width:300px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <div class="contain">
                        <b><input type="button" onclick="Addflight()" value="Add Flights" style="padding:10px; color:navy;" /></b>
                    </div>
                </div>
            </div>
        </div>&emsp;&emsp;&emsp;&emsp;&emsp;
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="images\img1.png" alt="Avatar" style="width:300px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <div class="contain">
                        <b><input type="button" onclick="Viewflight()" value="View Flights" style="padding:10px; color:navy;" /></b>
                    </div>
                </div>
            </div>
        </div>&emsp;&emsp;&emsp;&emsp;&emsp;
        <div class="flip-card">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img src="images\img6.png" alt="Avatar" style="width:300px;height:300px;">
                </div>
                <div class="flip-card-back">
                    <div class="contain">
                        <b><input type="button" onclick="ViewUser()" value="View Users" style="padding:10px; color:navy;" /></b>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container">

        <main role="main" class="pb-3">

            @RenderBody()

        </main>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <section>
        <script>
            function Addflight() {
                window.open("http://localhost:5107/Flights/Create")
            }
            function Viewflight() {
                window.open("http://localhost:5107/Flights/Details")
            }
            function ViewUser() {
                window.open("http://localhost:5107/AdminLogin/Details")
            }
        </script>

    </section>

    <footer style="position:relative">
        <p style="text-align:left;">
            <b>COMPANY</b>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>HELP</b><br />
            About Us&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Help Center<br />
            ContactUs<span style='font-size:20px;'>&#9990;</span>

            -122-6454&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;Privacy Policy
        </p>
        <hr />
        <div style="text-align:left;">
            <p>
                &copy; JXTravels All rights reserved.
                <br />
                <br />
                <span class="btn"><i class="fa fa-facebook"></i></span>
                <span class="btn"><i class="fa fa-instagram"></i></span>
                <span class="btn"><i class="fa fa-twitter"></i></span>
            </p>
        </div>

    </footer>

</body>

</html>

FlightBookingApp/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Flight Home Page</title>

    <style>

        body {
            background-image: url("bgimg1.jfif");
            background-repeat: no-repeat;
            background-size: cover;
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
        }

        header {
            background-color: navy;
            color: aliceblue;
            padding: 20px;
            text-align: center;
        }

        nav {
            color: aliceblue;
            padding: 9px 0;
            text-align: left;
        }

            nav a {
                color: aliceblue;
                text-decoration: none;
                margin: 0 10px;
            }

        section {
            padding: 20px;
            text-align: center;
            display: flex;
        }

        footer {
            background-color: grey;
            color: #fff;
            padding: 10px;
            text-align: right;
            position: fixed;
            bottom: 0;
            width: 100%;
            height: 23%;
        }

        .container {
            width: 100%;
            height: 100vh;
            display: flex;
            justify-content: center;
            align-items: start;
        }

        .contain {
            margin: 0;
            position: absolute;
            top: 50%;
            left: 50%;
            -ms-transform: translate(-50%, -50%);
            transform: translate(-50%, -50%);
        }

        .btn {
            border: none;
            color: white;
            padding: 12px 16px;
            font-size: 16px;
            cursor: pointer;
        }
    </style>
</head>


<body>

    <header>

        <nav>

            <a href="#"><u>JXTravels</u> </a>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;

            &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
            <a href="http://localhost:5107/Flights/Create" class="btn btn-info">Add Flights</a> &emsp;

            <a href="http://localhost:5107/Flights/Details" class="btn btn-info">View Flights</a> &emsp;

            <a href="http://localhost:5107/AdminLogin/Details" class="btn btn-info">View Users</a> &emsp;

            <span style='font-size:25px;'>&#128075;</span><b>Hello Admin</b>
            <!--&#10068;-->

        </nav>

    </header>


    <div class="container">

        <main role="main" class="pb-3">

            @RenderBody()

        </main>

    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>

    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>

    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)

    <footer>
        <p style="text-align:left;">
            <b>COMPANY</b>&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;<b>HELP</b><br />
            About Us&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;Help Center<br />
            ContactUs<span style='font-size:20px;'>&#9990;</span>

            -122-6454&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&nbsp;Privacy Policy
        </p>
        <hr />
        <div style="text-align:left;">
            <p>
                &copy; JXTravels All rights reserved.&emsp;&emsp;&emsp;&emsp;&emsp;&emsp; &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                &emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;&emsp;
                <span class="btn"><i class="fa fa-facebook"></i></span>
                <span class="btn"><i class="fa fa-instagram"></i></span>
                <span class="btn"><i class="fa fa-twitter"></i></span>
            </p>
        </div>

    </footer>

</body>

</html>